/*
 * ============================================================
 * FILE: schema.mjs
 * PURPOSE: Defines and validates the controlled specification schema accepted by Mini Tool Factory.
 * ============================================================
 */

const INPUT_KEY=/^[a-z][A-Za-z0-9]*$/;const ID=/^[a-z][a-z0-9-]{2,62}$/;const OPS=new Set(["constant","input","add","subtract","multiply","divide","power","sqrt","negate"]);const finite=(value,label)=>{if(typeof value!=="number"||!Number.isFinite(value))throw new Error(`${label} must be a finite number.`);return value};const plain=(value,label)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be an object.`);return value};
function validateExpression(node,inputKeys,depth=0){plain(node,"Expression node");if(depth>16)throw new Error("Expression nesting exceeds the safe limit.");if(!OPS.has(node.op))throw new Error(`Expression operation ${String(node.op)} is not allowed.`);if(node.op==="constant"){finite(node.value,"Constant");return}if(node.op==="input"){if(typeof node.key!=="string"||!inputKeys.has(node.key))throw new Error("Expression input must reference a declared input key.");return}if(node.op==="sqrt"||node.op==="negate"){validateExpression(node.value,inputKeys,depth+1);return}if(!Array.isArray(node.values)||node.values.length<2||node.values.length>12)throw new Error(`${node.op} requires two to twelve child expressions.`);node.values.forEach(value=>validateExpression(value,inputKeys,depth+1));}
export function validateToolSpec(spec){plain(spec,"Tool specification");if(spec.version!=="mini-tool-factory/v1")throw new Error("Unsupported tool specification version.");if(spec.kind!=="calculator")throw new Error("Only calculator specifications are supported by the controlled runtime.");if(typeof spec.id!=="string"||!ID.test(spec.id))throw new Error("Specification id must be a lowercase slug of 3–63 characters.");for(const key of ["name","description","formula"]){if(typeof spec[key]!=="string"||!spec[key].trim()||spec[key].length>400)throw new Error(`${key} must be a non-empty string of at most 400 characters.`)}if(!Array.isArray(spec.inputs)||spec.inputs.length<1||spec.inputs.length>8)throw new Error("A specification must contain one to eight inputs.");const keys=new Set;for(const input of spec.inputs){plain(input,"Input");if(typeof input.key!=="string"||!INPUT_KEY.test(input.key)||keys.has(input.key))throw new Error("Each input needs a unique camelCase key.");keys.add(input.key);for(const key of ["label","unit"]){if(typeof input[key]!=="string"||input[key].length>100)throw new Error(`Input ${key} must be a short string.`)}if(input.type!=="number")throw new Error("Only number inputs are supported.");if("min" in input)finite(input.min,"Input minimum");if("max" in input)finite(input.max,"Input maximum");if("min" in input&&"max" in input&&input.min>input.max)throw new Error("Input minimum cannot exceed maximum.");finite(input.example,"Input example");}plain(spec.output,"Output");for(const key of ["label","unit"]){if(typeof spec.output[key]!=="string"||spec.output[key].length>100)throw new Error(`Output ${key} must be a short string.`)}validateExpression(spec.expression,keys);if(!Array.isArray(spec.tests)||spec.tests.length<1||spec.tests.length>6)throw new Error("A specification must include one to six deterministic test cases.");for(const item of spec.tests){plain(item,"Test case");plain(item.input,"Test input");finite(item.expected,"Test expected result");for(const input of spec.inputs)finite(item.input[input.key],`Test input ${input.key}`)}return spec;}
export function cloneSpec(spec){return JSON.parse(JSON.stringify(spec));}
