import { cloneSpec,validateToolSpec } from "./schema.mjs";
const constant=value=>({op:"constant",value}),input=key=>({op:"input",key}),multiply=(...values)=>({op:"multiply",values}),divide=(...values)=>({op:"divide",values}),add=(...values)=>({op:"add",values});
export const TEMPLATES={
 threePhasePower:{version:"mini-tool-factory/v1",id:"balanced-three-phase-real-power",kind:"calculator",name:"Balanced three-phase real power",description:"Calculates balanced sinusoidal three-phase real power from line-to-line voltage, line current, and power factor.",formula:"P (kW) = √3 × VL × IL × PF ÷ 1000",inputs:[{key:"lineVoltage",label:"Line-to-line voltage",unit:"V",type:"number",min:0.000001,example:400},{key:"lineCurrent",label:"Line current",unit:"A",type:"number",min:0,example:10},{key:"powerFactor",label:"Power factor",unit:"",type:"number",min:0,max:1,example:.8}],expression:divide(multiply({op:"sqrt",value:constant(3)},input("lineVoltage"),input("lineCurrent"),input("powerFactor")),constant(1000)),output:{label:"Real power",unit:"kW"},tests:[{input:{lineVoltage:400,lineCurrent:10,powerFactor:.8},expected:5.542562584220407}]},
 ohmsVoltage:{version:"mini-tool-factory/v1",id:"ohms-law-voltage",kind:"calculator",name:"Ohm's law voltage",description:"Calculates voltage from a stated current and resistance.",formula:"V = I × R",inputs:[{key:"current",label:"Current",unit:"A",type:"number",min:0,example:2},{key:"resistance",label:"Resistance",unit:"Ω",type:"number",min:0,example:12}],expression:multiply(input("current"),input("resistance")),output:{label:"Voltage",unit:"V"},tests:[{input:{current:2,resistance:12},expected:24}]},
 celsiusFahrenheit:{version:"mini-tool-factory/v1",id:"celsius-to-fahrenheit",kind:"calculator",name:"Celsius to Fahrenheit",description:"Converts a Celsius temperature to Fahrenheit.",formula:"°F = °C × 9 ÷ 5 + 32",inputs:[{key:"celsius",label:"Temperature",unit:"°C",type:"number",min:-273.15,example:25}],expression:add(divide(multiply(input("celsius"),constant(9)),constant(5)),constant(32)),output:{label:"Temperature",unit:"°F"},tests:[{input:{celsius:25},expected:77}]},
 rectangleArea:{version:"mini-tool-factory/v1",id:"rectangle-area",kind:"calculator",name:"Rectangle area",description:"Calculates a rectangle area from length and width entered in the same unit.",formula:"Area = length × width",inputs:[{key:"length",label:"Length",unit:"m",type:"number",min:0,example:4},{key:"width",label:"Width",unit:"m",type:"number",min:0,example:3}],expression:multiply(input("length"),input("width")),output:{label:"Area",unit:"m²"},tests:[{input:{length:4,width:3},expected:12}]}
};
for(const template of Object.values(TEMPLATES))validateToolSpec(template);export function availableTemplates(){return Object.entries(TEMPLATES).map(([key,value])=>({key,name:value.name,description:value.description}))}export function generateToolSpec(prompt){if(typeof prompt!=="string"||!prompt.trim())throw new Error("Describe one supported calculator or choose a deterministic template.");const text=prompt.toLowerCase();let key;if(/three[ -]?phase|3[ -]?phase/.test(text)&&/power|kw|kilowatt/.test(text))key="threePhasePower";else if(/ohm|voltage|v\s*=\s*i/.test(text))key="ohmsVoltage";else if(/celsius|fahrenheit|temperature/.test(text))key="celsiusFahrenheit";else if(/rectangle|area/.test(text))key="rectangleArea";else throw new Error("This safe MVP supports three-phase power, Ohm's-law voltage, Celsius-to-Fahrenheit, and rectangle-area calculators. Refine the description or select a template.");return cloneSpec(TEMPLATES[key]);}
